title: "DUKE WHISKERPANTS"
logo: "/assets/images/Gemini_Generated_Image_x8njc2x8njc2x8nj.jpeg"
description: "I’ve mastered training machines to do my work (and sometimes explain it to me). I’ve turned coffee into code and pretended to understand complex algorithms. Now navigating Earth one project at a time."
show_downloads: false
theme: jekyll-theme-minimal
