title: Vitasta Verma
#logo: /Users/vitastaverma/Documents/Vitasta/Personal/Documents/Screenshot 2025-02-04 at 11.54.02 AM.png
description: Student @BITS Pilani
show_downloads: false
theme: jekyll-theme-minimal
