title: DUKE WHISKERPANTS
logo: https://github.com/v-square007/portfolio_githubthemes/blob/9ddd5d5b7569e610c87e30bc19965998f16582c1/images/Gemini_Generated_Image_x8njc2x8njc2x8nj.jpeg
description: Student @BITS Pilani
show_downloads: false
theme: jekyll-theme-minimal
