title: "DUKE WHISKERPANTS"
logo: "/assets/images/Gemini_Generated_Image_x8njc2x8njc2x8nj.jpeg"
description: "With a Master’s in Data Science, I’ve learned how to train machines to do my homework (and occasionally explain it to me). Before that, I earned a Bachelor’s in Computer Science, where I became an expert at turning coffee into code and pretending to understand complex algorithms. Now, I’m navigating the tech world, one project (and snack) at a time."
show_downloads: false
theme: jekyll-theme-minimal
