title: Vitasta Verma
logo: https://github.com/v-square007/portfolio_githubthemes/blob/9769ed5e4be038d7580d925557631a3cec89b396/Gemini_Generated_Image_x8njc2x8njc2x8nj.jpeg
description: Student @BITS Pilani
#show_downloads: false
theme: jekyll-theme-minimal
